// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP1LpQJBjB88PdcNME-SdGCOT9HDdgrMY',
    appId: '1:1051008114248:web:f3de192b86fff5aad4827d',
    messagingSenderId: '1051008114248',
    projectId: 'skillswap-c1e3d',
    authDomain: 'skillswap-c1e3d.firebaseapp.com',
    storageBucket: 'skillswap-c1e3d.firebasestorage.app',
    measurementId: 'G-CLZET4K25W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA92dfipO51_z0Yn67S0ekB9lcor-Saqsw',
    appId: '1:1051008114248:android:96c0c540e065b663d4827d',
    messagingSenderId: '1051008114248',
    projectId: 'skillswap-c1e3d',
    storageBucket: 'skillswap-c1e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQvB-_wA7sLMlCIPcG4LwOwaysd_VOjRs',
    appId: '1:1051008114248:ios:a5490f29041cb009d4827d',
    messagingSenderId: '1051008114248',
    projectId: 'skillswap-c1e3d',
    storageBucket: 'skillswap-c1e3d.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQvB-_wA7sLMlCIPcG4LwOwaysd_VOjRs',
    appId: '1:1051008114248:ios:a5490f29041cb009d4827d',
    messagingSenderId: '1051008114248',
    projectId: 'skillswap-c1e3d',
    storageBucket: 'skillswap-c1e3d.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP1LpQJBjB88PdcNME-SdGCOT9HDdgrMY',
    appId: '1:1051008114248:web:6b01aad8da10dc07d4827d',
    messagingSenderId: '1051008114248',
    projectId: 'skillswap-c1e3d',
    authDomain: 'skillswap-c1e3d.firebaseapp.com',
    storageBucket: 'skillswap-c1e3d.firebasestorage.app',
    measurementId: 'G-5QR2GE50ZD',
  );
}
